excerpt_separator: ""
pygments: rouge
markdown: kramdown
url: http://blog.tieks4.tk
name: Tieks4
description: ""
author: Tieks
avatar: http://gravatar.com/avatar/4cf519dc46b9fd28fdf3881fc1e14fc6?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 
